### ISSUE TITLE
Análisis del esquema actual

### ISSUE THREAD

**Issue by arturorc** [dgb-sistemas/biblat-schema#1]
## Criterios de aceptación

* Lista de catálogos
* Diccionario de datos

## Duración

* 11 días, 1 hora

**Comment by arturorc** [comment]
## Catálogos

| Campo | Etiqueta | Requerido| Sugerencia |
|--------|----------|:---------:|-------------|
| País de la revista | 008e | :heavy_check_mark: | [ISO 3166](https://www.iso.org/iso-3166-country-codes.html) \| [MARC](https://www.loc.gov/marc/countries/countries_code.html) |
| Idioma | 041a | :heavy_check_mark: | [ISO 639](https://www.iso.org/iso-639-language-codes.html) \| [MARC](https://www.loc.gov/marc/languages/language_code.html)|
| Idioma del resumen | 546a | | **Idioma** |
| Tipo de documento | 590a | :heavy_check_mark: | [Manual de indización (Anexo 2)](https://biblat.unam.mx/archivos/anexo2-tiposdedocumento.pdf) |
| Enfoque del documento | 590b | :heavy_check_mark: | [Manual de indización (Anexo 3)](https://biblat.unam.mx/archivos/anexo3-enfoque.pdf) |
| Disciplinas | 650a | :heavy_check_mark: | [Manual de indización (Anexo 4)](https://biblat.unam.mx/archivos/anexo4-disciplinas.pdf) |
| Sub-disciplinas | 653a (es) <br/> 654a (en) | | [Manual de indización (Anexo 5)](https://biblat.unam.mx/archivos/anexo5-subdisciplinas.pdf) |
| Descriptores geográficos | 653a (es) <br/> 654a (en) | | [Manual de indización (Anexo 6)](https://biblat.unam.mx/archivos/anexo6-codigosgeograficos.pdf) |
| Disciplina de la revista | 698a | :heavy_check_mark: | [Biblat](https://biblat.unam.mx/es/clase-y-periodica)

**Comment by arturorc** [comment]
# Diccionario de datos (Borrador)

## Revista

| Campo | Etiqueta | Requerido | Catágolo |
|-------|:--------:|:---------:|----------|
| Base de datos | | :heavy_check_mark: | Base de datos |
| Título de la revista | 222a | :heavy_check_mark: | |
| Título abreviado de la revista | 210a | | |
| ISSN | 022a | :heavy_check_mark: | |
| ISSN electrónico |  | | |
| País de la revista | 008e | :heavy_check_mark: | País de la revista |
| Disciplina de la revista | 698a | :heavy_check_mark: | Disciplina de la revista |
| Licencia CC | | | |
| Sherpa romeo | | | |
| Idiomas | | | |
| Logo | | | |
| Portada | | | |

**Comment by iselagb27** [comment]
**Catálogos:**
En el archivo **tag_text.dat** (pc_tab/catalog) de Aleph están definidos los catálogos para las etiquetas:
008 - País de la revista
041 - Idioma del documento
100 - País del Autor
546 - Idioma del resumen
590 - Tipo de documento
650 - Disciplina
653 - Palabra clave
698 - Disciplina de la Revista

**Comment by iselagb27** [comment]
Considero importante mantener un histórico de los analistas que van trabajando los registros (etiquetas CAT en Aleph)

**Comment by iselagb27** [comment]
**Observaciones:**
a. La etiqueta 036a sí se sigue usando, pero puede ser controlada por el mismo sistema ya que corresponde a la fecha de ingreso.
b. La etiqueta 504a solo indica si el documento contiene referencias utilizando la abreviatura **Refs.**, en caso contrario la etiqueta queda vacía, podría manejarse como un dato lógico.
c. Para la etiqueta 300c, podría manejarse en un solo campo, tipo str (ejemplo: ene-jun, may)
d. Considero que la paginación (300e) es un atributo del *Fascículo*.
e. Analizar conjuntamente con el usuario, cómo hacer distinción entre las subdisciplinas y las palabras clave o keywords, ya que actualmente se registran en la misma etiqueta.
f. La referencia(100z) del autor debe ser requerida para relacionarla con la institución

**Comment by arturorc** [comment]
@iselagb27, @mectiva se agregaron las correcciones de acuerdo a las observaciones.

@mectiva
* La etiqueta *036a* solo quedara en el registro marc no para captura.
* Hay que considerar agregar un número secuencial para mantener *035a*.
* La etiqueta *852* solo aparecerá en el registro marc.

@iselagb27 
* Para el caso de la etiqueta *300c* es preferible que el usuario capture con un combo el rango de meses y se mantenga el formato en el campo marc.
* El campo *300e* contempla la paginación del documento, por lo que no es un campo fijo del fascículo.
* Para el caso de las subdisciplinas lo que se tiene que ver con el usuario es el orden, me parece que teniendo una coincidencia de subdisciplina en palabras clave o keywords las podemos separar de acuerdo al catálogo de subdisciplinas.
* La referencia *100z* del autor no es requerida, ya que existen autores que pueden no tener afiliación.

**Comment by EJAJDGB** [comment]
![derbiblat](https://user-images.githubusercontent.com/39131627/40745319-c18663c6-641c-11e8-91a9-30cd19e1fe05.png)

DER Biblat_catalogos

**Comment by EJAJDGB** [comment]
-- MySQL dump 10.13  Distrib 5.7.22, for Linux (x86_64)
--
-- Host: localhost    Database: biblat_catalogos
-- ------------------------------------------------------
-- Server version	5.7.22-0ubuntu0.16.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `descriptores_geograficos`
--

DROP TABLE IF EXISTS `descriptores_geograficos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `descriptores_geograficos` (
  `id_geograficos` int(11) NOT NULL AUTO_INCREMENT,
  `nombre_geografico` varchar(250) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id_geograficos`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `descriptores_geograficos`
--

LOCK TABLES `descriptores_geograficos` WRITE;
/*!40000 ALTER TABLE `descriptores_geograficos` DISABLE KEYS */;
/*!40000 ALTER TABLE `descriptores_geograficos` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `disciplinas`
--

DROP TABLE IF EXISTS `disciplinas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `disciplinas` (
  `id_disciplina` int(10) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(150) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id_disciplina`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `disciplinas`
--

LOCK TABLES `disciplinas` WRITE;
/*!40000 ALTER TABLE `disciplinas` DISABLE KEYS */;
/*!40000 ALTER TABLE `disciplinas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `enfoque_documentos`
--

DROP TABLE IF EXISTS `enfoque_documentos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `enfoque_documentos` (
  `id_enfoque` int(10) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(150) CHARACTER SET latin1 DEFAULT NULL,
  `descripcion` varchar(700) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id_enfoque`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `enfoque_documentos`
--

LOCK TABLES `enfoque_documentos` WRITE;
/*!40000 ALTER TABLE `enfoque_documentos` DISABLE KEYS */;
/*!40000 ALTER TABLE `enfoque_documentos` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `idiomas`
--

DROP TABLE IF EXISTS `idiomas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `idiomas` (
  `id_idioma` int(10) NOT NULL AUTO_INCREMENT,
  `codigo` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `nombre` varchar(250) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id_idioma`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `idiomas`
--

LOCK TABLES `idiomas` WRITE;
/*!40000 ALTER TABLE `idiomas` DISABLE KEYS */;
/*!40000 ALTER TABLE `idiomas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `paises`
--

DROP TABLE IF EXISTS `paises`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `paises` (
  `id_pais` int(10) NOT NULL AUTO_INCREMENT,
  `codigo` varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  `nombre` varchar(250) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id_pais`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `paises`
--

LOCK TABLES `paises` WRITE;
/*!40000 ALTER TABLE `paises` DISABLE KEYS */;
/*!40000 ALTER TABLE `paises` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `sub_disciplinas`
--

DROP TABLE IF EXISTS `sub_disciplinas`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `sub_disciplinas` (
  `idsub_disciplinas` int(11) NOT NULL AUTO_INCREMENT,
  `id_disciplina` int(10) NOT NULL,
  `nombre` varchar(250) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`idsub_disciplinas`),
  KEY `fk_sub_disciplinas_disciplinas_idx` (`id_disciplina`),
  CONSTRAINT `fk_sub_disciplinas_disciplinas` FOREIGN KEY (`id_disciplina`) REFERENCES `disciplinas` (`id_disciplina`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `sub_disciplinas`
--

LOCK TABLES `sub_disciplinas` WRITE;
/*!40000 ALTER TABLE `sub_disciplinas` DISABLE KEYS */;
/*!40000 ALTER TABLE `sub_disciplinas` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `tipo_documentos`
--

DROP TABLE IF EXISTS `tipo_documentos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tipo_documentos` (
  `id_doc` int(10) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(150) CHARACTER SET latin1 DEFAULT NULL,
  `descripcion` varchar(700) CHARACTER SET latin1 DEFAULT NULL,
  PRIMARY KEY (`id_doc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `tipo_documentos`
--

LOCK TABLES `tipo_documentos` WRITE;
/*!40000 ALTER TABLE `tipo_documentos` DISABLE KEYS */;
/*!40000 ALTER TABLE `tipo_documentos` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-05-30 15:19:52
