### ISSUE TITLE
Descripción Bibliográfica Internacional Normalizada (ISBD)

### ISSUE THREAD

**Issue by ssballesterose** [dgb-sistemas/biblat-schema#23]
¿Impacta el uso de la Descripción Bibliográfica Internacional Normalizada (ISBD) en el parseo y/o normalización de datos?

https://www.ifla.org/files/assets/hq/publications/series/44-es.pdf

**Comment by arturorc** [comment]
En CLASE y PERIÓDICA no se usa ISBD
Como tal solo hay una convención  para el registro de la etiqueta 120:
120u,
120v,
120w.
120x
