### ISSUE TITLE
Creación de catálogos (indices) en el MDB elegido

### ISSUE THREAD

**Issue by arturorc** [dgb-sistemas/biblat-schema#5]
## Criterios de aceptación

* Estructura de catálogos en la BD.

## Duración

* 1 día 2 hrs

**Comment by mectiva** [comment]
ok se revisara estructura propuesta hasta el momento

**Comment by israeldch** [comment]
Para el catálogo de país propongo:
Etiqueta: 008e
Nombre en Inglés
Nombre en Español
Alpha – 2 code
Código Numerico
Uso de ISO 3166
Para el catálogo de idioma
Etiqueta: 041a
Nombre en Inglés
Nombre en Español
Uso de ISO 639 - 2
Para el catálogo de Tipo de documento
Etiqueta: 590a
Nombre en Español
Colocar código numérico
Para el catálogo de Enfoque del documento
Etiqueta: 590b
Nombre en Español
Identificador 
Para el catálogo de Disciplinas
Etiqueta: 650a
Nombre en Español
Identificador 
Para el catálogo de Sub-Disciplinas
Etiqueta: 653a, 654a
Nombre en Español
Nombre en Inglés
Identificador 
Para el catálogo de descriptores geográficos
Etiqueta: 653a, 654a
Nombre en Español
Nombre en Inglés
Identificador 
Para el catálogo disciplina de la revista
Etiqueta: 698a
Nombre en Español
Identificador 
Para el Catalogo Licencia
Etiqueta provisional
Nombre
Identificador 

Para el catálogo Colores RoMEO

Etiqueta provisional: 
Nombre en Español de la Política
Color de la política español
Color de la política inglés
Identificador

**Comment by arturorc** [comment]
@israeldch puedes editar tu comentario y darle formato?
Poner los campos en formato de tabla, negritas, etc.
Nota: Se las tablas se pueden copiar y pegar de word

**Comment by israeldch** [comment]
[catalogos.docx](https://github.com/dgb-sistemas/biblat-schema/files/2055664/catalogos.docx)

**Comment by EJAJDGB** [comment]
En estos catalogos, ¿Debemos de incluir a que etiqueta pertenecen? Segun yo, esta etiqueta pertenece al documento en cuestion (revista, fasciculo, etc). ¿Es correcto?

**Comment by arturorc** [comment]
Es correcto la etiqueta no debe formar parte del catálogo

**Comment by arturorc** [comment]
De acuerdo con los catálogos definidos

> ## Catálogos
> | Campo | Etiqueta | Sugerencia |
> |--------|---------|-------------|
> | Base de datos | | Identificador y nombre de la base |
> | País de la revista | 008e | [ISO 3166](https://www.iso.org/iso-3166-country-codes.html) \| [MARC](https://www.loc.gov/marc/countries/countries_code.html) |
> | Idioma | 041a | [ISO 639](https://www.iso.org/iso-639-language-codes.html) \| [MARC](https://www.loc.gov/marc/languages/language_code.html)|
> | Tipo de documento | 590a | [Manual de indización (Anexo 2)](https://biblat.unam.mx/archivos/anexo2-tiposdedocumento.pdf) |
> | Enfoque del documento | 590b | [Manual de indización (Anexo 3)](https://biblat.unam.mx/archivos/anexo3-enfoque.pdf) |
> | Disciplinas | 650a | [Manual de indización (Anexo 4)](https://biblat.unam.mx/archivos/anexo4-disciplinas.pdf) |
> | Sub-disciplinas | 653a (es) <br/> 654a (en) | [Manual de indización (Anexo 5)](https://biblat.unam.mx/archivos/anexo5-subdisciplinas.pdf) |
> | Descriptores geográficos | 653a (es) <br/> 654a (en) | [Manual de indización (Anexo 6)](https://biblat.unam.mx/archivos/anexo6-codigosgeograficos.pdf) |
> | Disciplina de la revista | 698a | [Biblat](https://biblat.unam.mx/es/clase-y-periodica)
> | Licencia CC | | |
> | SHERPA/RoMEO | | [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/definitions.php?la=es&fIDnum=%7C&mode=simple&version=#colours) |

Ver más factible las recomendaciones de @EJAJDGB 

> ![derbiblat](https://user-images.githubusercontent.com/39131627/40745319-c18663c6-641c-11e8-91a9-30cd19e1fe05.png)

por la relación de la Disciplina con su subdisciplina, pero falta la integración  de internacionalización que propone @israeldch, pero con algunos ajustes y utilizando las ventajas de MongoDB

Propongo que los catálogos con soporte de internacionalización se manejen como en el ejemplo siguiente:
# Disciplina
```json
{
    "_id": "d543efed1f1d4a2191c875aeccb78c05",
    "nombre": {
        "es": "Medicina",
        "en": "Medicine"
    }
}
```

Subdisciplina
```json
{
    "_id": "0aa680df41e84fe08518e5aa3e986597",
    "disciplina_id": "d543efed1f1d4a2191c875aeccb78c05",
    "nombre": {
        "es": "Anatomía humana",
        "en": "Human anatomy"
    }
}
```

**Comment by iduranm** [comment]
# Observaciones de los catálogos (Esquema de catálogos en la Documental)

**Países revistas**
- Se escogió alpha-3 porque existen códigos de países de 3 dígitos en MARC

**Idiomas**
-
