### ISSUE TITLE
Generación de programas de parseo y normalización de los datos para los catálogos

### ISSUE THREAD

**Issue by arturorc** [dgb-sistemas/biblat-schema#7]
## Criterio de aceptación

*  Datos importados

## Duración

* 7 días, 2 horas

**Comment by iduranm** [comment]
## Duda Arthur

@arturorc sobre este parseo tú nos comentaste en una reunión que ya tenías un .py que extraía la información de clase y periódica. Lo tendrás?

**Comment by arturorc** [comment]
> Duda Arthur
> @arturorc sobre este parseo tú nos comentaste en una reunión que ya tenías un .py que extraía la información de clase y periódica. Lo tendrás? Porque @mariogama y yo haremos ese parseo!

@iduranm para este proceso es necesario otro tipo de parseo y este dependerá la fuente de datos elegida para los catálogos, de igual forma dejo un script para el proceso de registros de ALEPH [seriunam.py](https://gist.github.com/arturorc/ce56a30784cff4b9be47b553f05ad2f8)

**Comment by arturorc** [comment]
Este issue se trabajará en dgb-sistemas/biblat_process#14
